   -- ONE ROW PER PRODUCTION BATCH: MES + LIMS + HISTORIAN
{{ config(materialized='table') }}

SELECT
        M.BATCH_ID
        ,M.SITE
        ,M.PRODUCTION_LINE
        ,M.PRODUCT_CODE
        ,M.THERAPY_AREA
        ,M.PLANNED_QTY
        ,M.ACTUAL_QTY
        ,M.YIELD_PCT
        ,M.BATCH_STATUS
        ,M.DEVIATION_FLAG
        ,M.START_TIME
        ,M.END_TIME
        ,M.BATCH_DURATION_HOURS
        ,M.YIELD_EXCEEDS_100
        ,M.END_BEFORE_START
        ,TO_DATE(M.START_TIME) AS START_DATE
        ,TO_DATE(M.END_TIME) AS END_DATE
        ,COALESCE(L.TEST_COUNT,0) AS TEST_COUNT
        ,COALESCE(L.FAILED_TEST_COUNT,0) AS FAILED_TEST_COUNT
        ,COALESCE(L.HAS_QUALITY_FAILURE,FALSE) AS HAS_QUALITY_FAILURE
        ,COALESCE(H.READING_COUNT,0) AS READING_COUNT
        ,COALESCE(H.ABNORMAL_READING_COUNT,0) AS ABNORMAL_READING_COUNT
        ,H.AVG_TEMPERATURE
        ,H.AVG_PRESSURE
        ,H.AVG_PH
        ,H.AVG_FLOW_RATE
        ,COALESCE(M.DEVIATION_FLAG = 'Yes', FALSE) OR COALESCE(L.HAS_QUALITY_FAILURE, FALSE) AS IS_PROBLEM_BATCH
FROM {{ ref('stg_mes') }} M
LEFT JOIN {{ ref('int_lims_by_batch') }} L
        ON M.BATCH_ID = L.BATCH_ID
LEFT JOIN {{ ref('int_historian_by_batch') }} H
        ON M.BATCH_ID = H.BATCH_ID