USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS PHARMA_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PHARMA;
CREATE SCHEMA IF NOT EXISTS PHARMA.SILVER;
CREATE SCHEMA IF NOT EXISTS PHARMA.GOLD;

SHOW SCHEMAS IN DATABASE PHARMA;


SHOW DATABASES LIKE 'PHARMA';