--SELECT CURRENT_USER();

-- Users and roles are created by USERADMIN
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS PHARMA_DEVELOPER;
GRANT ROLE PHARMA_DEVELOPER TO ROLE SYSADMIN;  -- SYSADMIN stays at the top and can see everything

CREATE USER IF NOT EXISTS AIMUN
  LOGIN_NAME = 'AIMUN'
  EMAIL = 'aimunanismasters@gmail.com'
  PASSWORD = 'Aimun@123'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = PHARMA_DEVELOPER
  DEFAULT_WAREHOUSE = PHARMA_WH
  DEFAULT_NAMESPACE = PHARMA.SILVER;

GRANT ROLE PHARMA_DEVELOPER TO USER AIMUN;
GRANT ROLE PHARMA_DEVELOPER TO USER SRUTHIITC1;

-- Object permissions are granted by the owner, SYSADMIN
USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE PHARMA_WH TO ROLE PHARMA_DEVELOPER;
GRANT USAGE, CREATE SCHEMA ON DATABASE PHARMA TO ROLE PHARMA_DEVELOPER;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA PHARMA.SILVER TO ROLE PHARMA_DEVELOPER;

GRANT USAGE ON STAGE PHARMA.SILVER.ADLS_SILVER_STAGE TO ROLE PHARMA_DEVELOPER;
GRANT USAGE ON FILE FORMAT PHARMA.SILVER.PARQUET_FF  TO ROLE PHARMA_DEVELOPER;

GRANT SELECT ON ALL TABLES    IN SCHEMA PHARMA.SILVER TO ROLE PHARMA_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMA.SILVER TO ROLE PHARMA_DEVELOPER;

USE ROLE SYSADMIN;
USE SCHEMA PHARMA.SILVER;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FF
  TYPE = PARQUET;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA PHARMA.GOLD   TO ROLE PHARMA_DEVELOPER;


GRANT USAGE ON FILE FORMAT PHARMA.SILVER.PARQUET_FF TO ROLE PHARMA_DEVELOPER;
GRANT SELECT ON ALL TABLES    IN SCHEMA PHARMA.SILVER TO ROLE PHARMA_DEVELOPER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMA.SILVER TO ROLE PHARMA_DEVELOPER;


--SHOW GRANTS TO ROLE PHARMA_DEVELOPER;

SHOW FUTURE GRANTS IN SCHEMA PHARMA.SILVER;

SHOW GRANTS OF ROLE PHARMA_DEVELOPER;