-- snowflake demo - pharma project
-- run one query at a time

USE ROLE PHARMA_DEVELOPER;
USE WAREHOUSE PHARMA_WH;
USE DATABASE PHARMA;


-- 1. schemas and gold tables
SHOW SCHEMAS IN DATABASE PHARMA;

SHOW TABLES IN SCHEMA PHARMA.GOLD;


-- 2. stage pointing to adls silver container (read + list only)
DESC STAGE PHARMA.SILVER.ADLS_SILVER_STAGE;

-- parquet files from databricks
LIST @PHARMA.SILVER.ADLS_SILVER_STAGE/export/mes/;


-- 3. silver counts - should be 500 / 1015 / 20173 / 500
SELECT 'MES' AS SOURCE_TABLE, COUNT(*) AS ROW_COUNT FROM PHARMA.SILVER.MES
UNION ALL
SELECT 'LIMS', COUNT(*) FROM PHARMA.SILVER.LIMS
UNION ALL
SELECT 'HISTORIAN', COUNT(*) FROM PHARMA.SILVER.HISTORIAN
UNION ALL
SELECT 'ERP', COUNT(*) FROM PHARMA.SILVER.ERP;


-- 4. gold counts - fact_batch 500, fact_quality_test 1000, dim_date 731
-- lims 1015 -> 1000 because 15 orphan tests removed
SELECT 'FACT_BATCH' AS GOLD_TABLE, COUNT(*) AS ROW_COUNT FROM PHARMA.GOLD.FACT_BATCH
UNION ALL
SELECT 'FACT_QUALITY_TEST', COUNT(*) FROM PHARMA.GOLD.FACT_QUALITY_TEST
UNION ALL
SELECT 'FACT_INVENTORY', COUNT(*) FROM PHARMA.GOLD.FACT_INVENTORY
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM PHARMA.GOLD.DIM_DATE;

-- check no batch lost or double counted - 500 / 500 / 1000 / 20133
SELECT COUNT(*) AS BATCH_ROWS
    ,COUNT(DISTINCT BATCH_ID) AS DISTINCT_BATCHES
    ,SUM(TEST_COUNT) AS TOTAL_TESTS
    ,SUM(READING_COUNT) AS TOTAL_READINGS
FROM PHARMA.GOLD.FACT_BATCH;


-- 5. quality results - pass 942, fail 44, oos 14
SELECT QUALITY_RESULT
    ,COUNT(*) AS TEST_COUNT
FROM PHARMA.GOLD.FACT_QUALITY_TEST
GROUP BY QUALITY_RESULT
ORDER BY TEST_COUNT DESC;

-- problem batches - 56 / 11.2%
SELECT COUNT_IF(IS_PROBLEM_BATCH) AS PROBLEM_BATCHES
    ,ROUND(100 * COUNT_IF(IS_PROBLEM_BATCH) / COUNT(*), 1) AS PROBLEM_PCT
FROM PHARMA.GOLD.FACT_BATCH;

-- problem batches by site
SELECT SITE
    ,COUNT(*) AS BATCHES
    ,COUNT_IF(IS_PROBLEM_BATCH) AS PROBLEM_BATCHES
    ,ROUND(100 * COUNT_IF(IS_PROBLEM_BATCH) / COUNT(*), 1) AS PROBLEM_PCT
FROM PHARMA.GOLD.FACT_BATCH
GROUP BY SITE
ORDER BY PROBLEM_PCT DESC;

-- abnormal readings - failed batches vs others (~5% vs 0.9%)
-- check column name
SELECT HAS_QUALITY_FAILURE
    ,SUM(ABNORMAL_READING_COUNT) AS ABNORMAL_READINGS
    ,SUM(READING_COUNT) AS TOTAL_READINGS
    ,ROUND(100 * SUM(ABNORMAL_READING_COUNT) / SUM(READING_COUNT), 1) AS ABNORMAL_PCT
FROM PHARMA.GOLD.FACT_BATCH
GROUP BY HAS_QUALITY_FAILURE;

-- stock risk - 52 below reorder, 10 overdue
-- check column names
SELECT COUNT_IF(BELOW_REORDER_FLAG) AS BELOW_REORDER
    ,COUNT_IF(DELIVERY_OVERDUE_FLAG) AS DELIVERY_OVERDUE
FROM PHARMA.GOLD.FACT_INVENTORY;


-- 6. snapshot - inventory history
-- valid_to empty = current row
SELECT INVENTORY_ID
    ,AVAILABLE_QTY
    ,INVENTORY_STATUS
    ,DBT_VALID_FROM
    ,DBT_VALID_TO
FROM PHARMA.GOLD.SNAP_ERP_INVENTORY
WHERE INVENTORY_ID = 'INV-0001'
ORDER BY DBT_VALID_FROM;


-- 7. cdc demo
-- raw - 13 rows, movement 1 twice (120 and 150)
SELECT MOVEMENT_ID
    ,QUANTITY
    ,SF_LOADED_AT
    ,SOURCE_FILE
FROM PHARMA.SILVER.CDC_DEMO_RAW
ORDER BY MOVEMENT_ID, SF_LOADED_AT;

-- gold - 12 rows, movement 1 once
-- only rows 1, 11, 12 updated in the last run
SELECT *
FROM PHARMA.GOLD.CDC_DEMO
ORDER BY DBT_UPDATED_AT DESC, MOVEMENT_ID;

-- load history - 2 files, 10 rows then 3 rows
SELECT FILE_NAME
    ,ROW_COUNT
    ,LAST_LOAD_TIME
FROM PHARMA.INFORMATION_SCHEMA.LOAD_HISTORY
WHERE TABLE_NAME = 'CDC_DEMO_RAW'
ORDER BY LAST_LOAD_TIME;


-- 8. extra
-- time travel - table 1 hour ago
SELECT COUNT(*) AS ROW_COUNT
FROM PHARMA.GOLD.FACT_BATCH AT (OFFSET => -3600);

-- queries run by dbt service user
SELECT QUERY_TEXT
    ,USER_NAME
    ,START_TIME
FROM TABLE(PHARMA.INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE USER_NAME = 'DBT_SERVICE'
ORDER BY START_TIME DESC
LIMIT 10;